In [ ]:
import numpy as np
#1

cicloA = []
for x in range(6):
    cicloA.append(x**2)
cicloA_comp = [y**2 for y in range(6)]

print(cicloA)
print(cicloA_comp)


cicloB = []
for n in range(20):
    if n%2 == 0:
        cicloB.append(n)
cicloB_comp = [m for m in range(20) if m%2 == 0]

print(cicloB)
print(cicloB_comp)


somma = 0
cicloC = []
for a in range(10):
    somma = somma + a
    cicloC.append(somma)
cicloC_comp = [sum(range(b+1)) for b in range(10)]

print(cicloC)
print(cicloC_comp)


[0, 1, 3, 6, 10, 15, 21, 28, 36, 45]
[0, 1, 3, 6, 10, 15, 21, 28, 36, 45]


In [ ]:
import numpy as np
#2

primi = np.array([2,3,5, 7])

print(len(primi))
print(primi.size)
print(primi.dtype)

def is_primo(n):
    if n<2:
        return False
    else:
        for i in range(2, int(n)):
            if n%i == 0:
                return False
    return True

primi_comp = [x for x in range(10) if is_primo(x)]

4
4
int64


In [13]:
import numpy as np
#3

a = np.arange(1, 7)
print(a)

b = a[1:4]
print(b)

c = a[::-1]
print(c)

print(a/c)

#liste
listA = list(range(1,7))
listB = listA[1:4]
listC = listA[::-1]

divisione = [x / y for x, y in zip(listA, listB)]
print(divisione)

[1 2 3 4 5 6]
[2 3 4]
[6 5 4 3 2 1]
[0.16666667 0.4        0.75       1.33333333 2.5        6.        ]
[0.5, 0.6666666666666666, 0.75]
