In [1]:
import random
lista = [random.randint(5, 15) for _ in range(20)]
print(lista)

[12, 14, 8, 12, 13, 11, 14, 15, 6, 13, 9, 7, 15, 15, 6, 13, 13, 5, 10, 11]


In [4]:
%%timeit

statistics.mean(lista)

16.8 μs ± 940 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [7]:
import numpy as np
statistics.mean(lista), np.mean(lista)

(11.1, np.float64(11.1))

In [10]:
#ndarray
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [7]:
import numpy as np
np.array([1,2.2, 3,4,5]).dtype
#oppure
a = np.array([1,2,3,4,5])
a.dtype

dtype('int64')

In [11]:
import numpy as np
zeri = np.zeros((3))
print(zeri)

[0. 0. 0.]


In [16]:
copia = np.zeros_like(a)
copia

array([0, 0, 0, 0, 0])